spring:
  application:
    name: commerceevolution
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/commerceevolutiondb}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

app:
  jwt:
    private-key: classpath:jwt/private.pem
    public-key: classpath:jwt/public.pem
    access-token-ttl: ${JWT_ACCESS_TOKEN_TTL:PT15M}
    refresh-token-ttl: ${JWT_REFRESH_TOKEN_TTL:P30D}
  media:
    upload-dir: ${MEDIA_UPLOAD_DIR:uploads}
    public-path: ${MEDIA_PUBLIC_PATH:/media}
